#!/usr/bin/env python3
"""Regenerate CHANGELOG.md from Conventional Commit messages in git history.

Behavior:
    - Reads `git log` from the current repo.
    - Parses subject lines matching `type(scope)?: subject`.
    - Groups commits by release tag (vX.Y.Z). Anything since the last tag
      goes under "Unreleased".
    - Within each release, groups by commit type into human-friendly sections.
    - Replaces the block between BEGIN/END AUTOGENERATED markers in
      CHANGELOG.md. Anything outside the markers is preserved verbatim.

Exit codes:
    0  success (CHANGELOG.md is up to date, or was just updated)
    1  unexpected failure
    2  not a git repo / no CHANGELOG.md
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHANGELOG = ROOT / "CHANGELOG.md"
BEGIN = "<!-- BEGIN AUTOGENERATED -->"
END = "<!-- END AUTOGENERATED -->"

# Conventional Commit types → human-readable section headings.
# Order here determines the order of sections in the output.
TYPE_SECTIONS: list[tuple[str, str]] = [
    ("feat",     "Features"),
    ("fix",      "Bug Fixes"),
    ("perf",     "Performance"),
    ("refactor", "Refactors"),
    ("docs",     "Documentation"),
    ("test",     "Tests"),
    ("build",    "Build"),
    ("ci",       "CI"),
    ("chore",    "Chores"),
    ("style",    "Style"),
    ("revert",   "Reverts"),
]
TYPE_ORDER = {t: i for i, (t, _) in enumerate(TYPE_SECTIONS)}
TYPE_LABEL = dict(TYPE_SECTIONS)

CC_RE = re.compile(
    r"^(?P<type>[a-z]+)(?:\((?P<scope>[^)]+)\))?(?P<bang>!)?:\s*(?P<subject>.+)$"
)


def run(*args: str) -> str:
    return subprocess.check_output(args, cwd=ROOT, text=True).strip()


def git_log() -> list[dict]:
    """Return list of {sha, subject, date, tag} for every commit, newest first."""
    try:
        raw = run(
            "git", "log",
            "--pretty=format:%H%x1f%s%x1f%cs%x1f%D",
            "--no-merges",
        )
    except subprocess.CalledProcessError:
        return []
    commits = []
    for line in raw.splitlines():
        if not line.strip():
            continue
        parts = line.split("\x1f")
        if len(parts) < 4:
            continue
        sha, subject, date, refs = parts
        tag = None
        for ref in refs.split(","):
            ref = ref.strip()
            m = re.match(r"tag:\s*(v\d+\.\d+\.\d+(?:[^,\s]*)?)", ref)
            if m:
                tag = m.group(1)
                break
        commits.append({"sha": sha, "subject": subject, "date": date, "tag": tag})
    return commits


def parse_cc(subject: str) -> dict | None:
    m = CC_RE.match(subject)
    if not m:
        return None
    d = m.groupdict()
    d["breaking"] = bool(d.get("bang"))
    return d


def group_into_releases(commits: list[dict]) -> list[dict]:
    """Walk commits newest→oldest, accumulating into a release whenever we
    hit a tag. The current head (everything before the first tag) is the
    'Unreleased' bucket."""
    releases: list[dict] = []
    current = {"name": "Unreleased", "date": None, "commits": []}
    for c in commits:
        current["commits"].append(c)
        if c["tag"]:
            current["name"] = c["tag"]
            current["date"] = c["date"]
            releases.append(current)
            current = {"name": "Unreleased", "date": None, "commits": []}
    if current["commits"] and current["name"] == "Unreleased":
        # Only emit Unreleased if it actually has commits.
        releases.insert(0, current)
    elif not releases and current["commits"]:
        releases.append(current)
    # Move Unreleased to top if it's not already there.
    releases.sort(key=lambda r: 0 if r["name"] == "Unreleased" else 1)
    return releases


def render_release(rel: dict) -> str:
    header = f"## [{rel['name']}]"
    if rel["date"]:
        header += f" — {rel['date']}"
    lines = [header, ""]
    by_type: dict[str, list[dict]] = {}
    other: list[dict] = []
    breaking: list[dict] = []
    for c in rel["commits"]:
        parsed = parse_cc(c["subject"])
        if not parsed:
            other.append(c)
            continue
        c["_parsed"] = parsed
        if parsed["breaking"]:
            breaking.append(c)
        by_type.setdefault(parsed["type"], []).append(c)

    if breaking:
        lines.append("### BREAKING CHANGES")
        lines.append("")
        for c in breaking:
            lines.append(format_commit(c))
        lines.append("")

    for t, label in TYPE_SECTIONS:
        bucket = by_type.get(t, [])
        if not bucket:
            continue
        lines.append(f"### {label}")
        lines.append("")
        for c in bucket:
            lines.append(format_commit(c))
        lines.append("")

    if other:
        lines.append("### Other")
        lines.append("")
        for c in other:
            lines.append(f"- {c['subject']} ({short(c['sha'])})")
        lines.append("")

    if not by_type and not other and not breaking:
        lines.append("_No commits._")
        lines.append("")

    return "\n".join(lines)


def format_commit(c: dict) -> str:
    p = c.get("_parsed") or {}
    subject = p.get("subject", c["subject"])
    scope = p.get("scope")
    prefix = f"**{scope}:** " if scope else ""
    return f"- {prefix}{subject} ({short(c['sha'])})"


def short(sha: str) -> str:
    return sha[:7]


def render_changelog(releases: list[dict]) -> str:
    if not releases:
        return "## [Unreleased]\n\n_No commits yet._\n"
    blocks = [render_release(r).rstrip() for r in releases]
    return "\n\n".join(blocks) + "\n"


def update_file(generated: str) -> bool:
    """Replace the AUTOGENERATED block in CHANGELOG.md. Returns True if the
    file changed on disk."""
    if not CHANGELOG.exists():
        sys.stderr.write(f"[changelog] CHANGELOG.md missing at {CHANGELOG}\n")
        sys.exit(2)
    old = CHANGELOG.read_text()
    if BEGIN not in old or END not in old:
        sys.stderr.write(
            f"[changelog] AUTOGENERATED markers missing in {CHANGELOG}\n"
        )
        sys.exit(2)
    pre, _, rest = old.partition(BEGIN)
    _, _, post = rest.partition(END)
    new = f"{pre}{BEGIN}\n\n{generated.strip()}\n\n{END}{post}"
    if new == old:
        return False
    CHANGELOG.write_text(new)
    return True


def main() -> int:
    commits = git_log()
    releases = group_into_releases(commits)
    generated = render_changelog(releases)
    changed = update_file(generated)
    if changed:
        print("[changelog] CHANGELOG.md updated.")
    else:
        print("[changelog] CHANGELOG.md already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
